import Home from "./Home";
import SEO from "@/components/SEO";

export default function Landing() {
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "Person",
    "name": "Saiesh Sasane",
    "jobTitle": "PCB Design & Embedded Systems Engineer",
    "url": typeof window !== "undefined" ? window.location.origin : "",
    "sameAs": [
      "https://github.com/Saie12"
    ],
    "knowsAbout": [
      "PCB Design",
      "Embedded Systems",
      "Hardware Engineering",
      "KiCad",
      "High-Speed Design",
      "Firmware Development",
      "ARM Cortex-M",
      "Circuit Design",
      "Hardware Prototyping"
    ],
    "description": "Professional PCB design and embedded systems engineer specializing in high-speed board design, firmware development, and hardware prototyping using KiCad, C++, and Python."
  };

  return (
    <>
      <SEO
        title="Home"
        description="Saiesh Sasane - Professional PCB Design & Embedded Systems Engineer specializing in high-speed board design, firmware development, KiCad, ARM Cortex-M, hardware prototyping, circuit design, and IoT devices. Expert in schematic capture, multi-layer PCB layout, impedance control, and DFM principles."
        keywords={[
          "Saiesh Sasane",
          "Saiesh",
          "PCB Design Engineer",
          "Embedded Systems Engineer",
          "Hardware Engineer",
          "KiCad Expert",
          "High-Speed PCB Design",
          "Circuit Board Design",
          "Schematic Design",
          "PCB Layout",
          "Firmware Development",
          "ARM Cortex-M",
          "Microcontroller Programming",
          "Hardware Prototyping",
          "IoT Hardware",
          "Embedded C Programming",
          "C++ Embedded",
          "Python Hardware",
          "Electronics Engineer",
          "Board Design",
          "Multi-layer PCB",
          "Impedance Control",
          "Differential Pairs",
          "Signal Integrity",
          "EMI EMC Design",
          "DFM Design for Manufacturing",
          "Gerber Files",
          "BOM Generation",
          "Pick and Place",
          "SMD Soldering",
          "THT Assembly",
          "Hardware Bring-up",
          "Circuit Testing",
          "Oscilloscope",
          "Logic Analyzer",
          "SPICE Simulation",
          "PIC Microcontroller",
          "8051 Microcontroller",
          "STM32",
          "ESP32",
          "Arduino",
          "Raspberry Pi",
          "Sensor Integration",
          "Power Supply Design",
          "Voltage Regulation",
          "Battery Management",
          "USB Design",
          "Ethernet Interface",
          "WiFi Hardware",
          "Bluetooth Hardware",
          "GPS Tracker",
          "Asset Tracking",
          "Smart Home Devices",
          "Home Automation",
          "Relay Control",
          "Motor Control",
          "LED Driver",
          "Display Interface",
          "Communication Protocols",
          "I2C",
          "SPI",
          "UART",
          "CAN Bus",
          "Modbus",
          "MQTT",
          "Real-time Systems",
          "RTOS",
          "FreeRTOS",
          "Bare Metal Programming",
          "Hardware Debugging",
          "JTAG",
          "SWD",
          "Version Control Hardware",
          "Git Hardware",
          "GitHub Hardware Projects",
          "Open Source Hardware",
          "Maker Projects",
          "DIY Electronics",
          "Electronics Prototyping",
          "Rapid Prototyping",
          "Product Development",
          "Hardware Consulting",
          "Freelance PCB Designer",
          "Contract Hardware Engineer",
          "Remote Hardware Engineer",
          "PCB Design Services",
          "Embedded Firmware Services",
          "Hardware Design Consultant",
          "Electronics Design Services",
          "Circuit Board Manufacturing",
          "PCB Fabrication",
          "PCB Assembly",
          "Turnkey PCB",
          "Prototype PCB",
          "Production PCB",
          "Industrial Electronics",
          "Consumer Electronics",
          "Medical Device Hardware",
          "Automotive Electronics",
          "Aerospace Electronics",
          "Robotics Hardware",
          "Drone Electronics",
          "Wearable Electronics",
          "Portable Devices",
          "Battery Powered Devices"
        ]}
        structuredData={structuredData}
      />
      <Home />
    </>
  );
}